name: Create Image and Push Using federated IDP

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # ðŸ‘ˆ required for OIDC JWT
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get OIDC token
        id: oidc
        run: |
          echo "Requesting OIDC token"
          RESPONSE=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=silly-snyder.container-registry.com")

          TOKEN=$(echo "$RESPONSE" | jq -r '.value')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

          # Pretty print the JWT token (header and payload)
          echo "=== JWT Header ==="
          echo "$TOKEN" | cut -d'.' -f1 | base64 -d 2>/dev/null | jq .
          echo ""
          echo "=== JWT Payload ==="
          echo "$TOKEN" | cut -d'.' -f2 | base64 -d 2>/dev/null | jq .

      - name: Build and Push Image
        run: |
          echo $TOKEN | docker login -u not-relevant --password-stdin silly-snyder.container-registry.com
          docker build -t silly-snyder.container-registry.com/library/image:${{ github.sha }} .

      - name: Pull Image from Registry
        run: |
          echo $TOKEN | docker login -u not-relevant --password-stdin silly-snyder.container-registry.com
          docker pull silly-snyder.container-registry.com/library/hello-world:latest
